### ISSUE TITLE
Todo API の OpenAPI 仕様基本定義を作成

### ISSUE THREAD

**Issue by tomotakashimizu** [tomotakashimizu/claude-code-todo-app#1]
# Todo API の OpenAPI 仕様基本定義を作成

## 概要

Todo 表示画面実装の第一歩として、OpenAPI 3.0 仕様で Todo API の基本定義を作成します。

## タスク内容

- [ ] `schema/openapi.yaml` ファイルの作成
- [ ] Todo データモデルの定義
- [ ] 基本的な API エンドポイント定義（GET /todos のみ）
- [ ] レスポンススキーマの定義

## 成果物

`schema/openapi.yaml` に以下を含む：

### データモデル

```yaml
components:
  schemas:
    Todo:
      type: object
      required:
        - id
        - title
        - completed
        - createdAt
      properties:
        id:
          type: string
          format: uuid
        title:
          type: string
          maxLength: 200
        description:
          type: string
          maxLength: 1000
        completed:
          type: boolean
        priority:
          type: string
          enum: [low, medium, high]
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
```

### API エンドポイント

- `GET /api/todos` - Todo 一覧取得

## 完了条件

- [ ] OpenAPI 仕様ファイルが作成されている
- [ ] `npm run validate:api` でバリデーションが通る
- [ ] Todo データモデルが適切に定義されている
- [ ] GET /todos エンドポイントが定義されている
